<a href="https://colab.research.google.com/github/RafsanJany-44/Research_Sleep_Stage_Classification/blob/main/LIME.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
data = 'https://raw.githubusercontent.com/RafsanJany-44/Thesis_Project/main/All_DATA/without_sn_and_Epoch/EEG_HMC.csv'
dataset = pd.read_csv(data)

In [ ]:
dataset.head()

Sleep Stage  MeanP_Alpha_F4  MedianF_Alpha_F4  MeanF_Alpha_F4  \
0           W         0.00051           8.74146        18.48195   
1           W         0.00040          10.24000        17.48293   
2           W         0.00036           9.74049        17.98244   
3           W         0.00035          10.11512        17.60780   
4           W         0.00033           9.74049        17.60780   

   Spectral Edge_Alpha_F4  PeakF_Alpha_F4  MeanP_Beta_F4  MedianF_Beta_F4  \
0                17.48293         8.24195        0.00071         19.73073   
1                16.85854        10.61463        0.00051         17.23317   
2                17.48293         8.74146        0.00047         17.60780   
3                17.10829         9.61561        0.00047         17.35805   
4                17.23317         8.11707        0.00043         17.23317   

   MeanF_Beta_F4  Spectral Edge_Beta_F4  ...  MeanP_Delta_O2  \
0       29.84585               33.84195  ...         0.00724   
1       26.34927               29.34634  ...         0.00723   
2       25.47512               28.22244  ...         0.00230   
3       26.47415               28.72195  ...         0.00091   
4       25.84976               28.09756  ...         0.00175   

   MedianF_Delta_O2  MeanF_Delta_O2  Spectral Edge_Delta_O2  PeakF_Delta_O2  \
0           0.74927         3.87122                 1.99805         0.87415   
1           0.49951         3.74634                 1.24878         0.49951   
2           0.62439         5.24488                 2.12293         0.62439   
3           0.87415         6.61854                 3.12195         0.62439   
4           0.49951         5.74439                 2.24780         0.49951   

   MeanP_Gamma_O2  MedianF_Gamma_O2  MeanF_Gamma_O2  Spectral Edge_Gamma_O2  \
0        0.000210          35.21561        42.20878                49.95122   
1        0.000095          34.34146        43.33268                49.95122   
2        0.000074          34.59122        45.95512                49.95122   
3        0.000082          32.46829        43.95707                49.95122   
4        0.000077          33.59220        44.83122                49.95122   

   PeakF_Gamma_O2  
0        49.95122  
1        49.95122  
2        49.95122  
3        49.95122  
4        49.95122  

[5 rows x 76 columns]

In [ ]:
X = dataset.iloc[:, 1:].values
y = dataset.iloc[:, 0].values

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.33, random_state = 0)

In [ ]:
X_train.shape, X_test.shape

((72662, 75), (35789, 75))

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train =sc.fit_transform(X_train)

X_test =sc.fit_transform(X_test)

**Tuning**

KNN

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
KNN_class = KNeighborsClassifier(n_neighbors=7)
KNN_class.fit(X_train, y_train)
y_pred_KNN=KNN_class.predict(X_test)

In [ ]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators=125, random_state=0)
classifier.fit(X_train, y_train)
y_pred_RF=classifier.predict(X_test)

In [ ]:
import xgboost as xgb
xgb_classifier = xgb.XGBClassifier(max_depth=14)
xgb_classifier.fit(X_train,y_train)
y_pred_XG = xgb_classifier.predict(X_test)

In [ ]:
from sklearn.metrics import accuracy_score
print("Accurecy KNN: ",accuracy_score(y_test, y_pred_KNN))
print("Accurecy RF: ",accuracy_score(y_test, y_pred_RF))
print("Accurecy XG: ",accuracy_score(y_test, y_pred_XG))


[[ 1675  1055    48   452   677]
 [  942 10052  1204   584   189]
 [   63  1224  5670    20    30]
 [  462   678    44  4235    94]
 [  956   356    27    87  4965]]
              precision    recall  f1-score   support

          N1       0.41      0.43      0.42      3907
          N2       0.75      0.77      0.76     12971
          N3       0.81      0.81      0.81      7007
           R       0.79      0.77      0.78      5513
           W       0.83      0.78      0.80      6391

    accuracy                           0.74     35789
   macro avg       0.72      0.71      0.71     35789
weighted avg       0.75      0.74      0.74     35789

Accurecy:  0.7431613065467043
